name: Deploy React App to Github Pages

on:
  push:
    branches:
      - "gh-pages"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-react-to-github-pages@v1.2.4
        with:
          path: dist # change to your build folder
